/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Daz (https://sketchfab.com/Darren.Hogan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nes-console-and-controller-ffd427134d5e44b4850628030aa66236
Title: NES Console and Controller
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap';
import { useGSAP } from '@gsap/react';

export default function Model(props) {
  const { nodes, materials } = useGLTF(`${import.meta.env.BASE_URL}models/nes.glb`)

  const group = useRef()

  useGSAP(() => {
    gsap.from(group.current.rotation, {
      y: Math.PI / 2,
      duration: 1,
      ease: 'power3.out'
    })
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-1.569, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.004, 0.004, 0.005]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials.WhitePlastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_5.geometry}
              material={materials.Misc}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6.geometry}
              material={materials.Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_7.geometry}
              material={materials.DarkPlastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_8.geometry}
              material={materials.LightPlastic}
            />
          </group>
          <group position={[0.018, -0.03, 0.259]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_10.geometry}
              material={materials.Cable}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_11.geometry}
              material={materials.WhitePlastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_12.geometry}
              material={materials.Misc}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_13.geometry}
              material={materials.Metal}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(`${import.meta.env.BASE_URL}models/nes.glb`)
