/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Vladislav Krutenyuk (https://sketchfab.com/vladkrutenyuk)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/robotic-arm-kuka-0211a7f80bdc48f784af6796913af96b
Title: Robotic Arm KUKA
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function RobotArm(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(`${import.meta.env.BASE_URL}models/robot_arm.glb`)
  const { actions } = useAnimations(animations, group)

   useEffect(() => {
        actions["Armature|Welding_1"]?.play()
    }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="4b856b684d1441c881ad17d652ffa765fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_94"
                      geometry={nodes.Object_94.geometry}
                      material={materials.Material}
                      skeleton={nodes.Object_94.skeleton}
                    />
                    <group name="Object_93" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                  </group>
                </group>
                <group name="KUKA" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(`${import.meta.env.BASE_URL}models/robot_arm.glb`)
